### ISSUE TITLE
Authentication don't work on Win10

### ISSUE THREAD

**Issue by alexamiryan** [Sajidur78/CredNet#1]
Hello. I am trying to write custom credentials provider with your library. I see new tile on the WIndows logon screen, however authentication doesn't pass.
I have verified that valid username, password and machine name are coming to CredentialSerializer.SerializeKerbInteractiveLogon function, but windows just doesn't login. 
I need to take a serialization, save it in my DB and then authorize the user after passing my own checks.
Can you please investigate into this issue, maybe I am doing something wrong?

**Comment by Sajidur78** [comment]
Could you provide an example project with the problem reproduced?

**Comment by alexamiryan** [comment]
Example project is a CredNet.Sample. I've added registry values, registed it for interop and it shows on login screen, but when I enter correct password, it just does nothing, it stays on the login screen.

**Comment by Sajidur78** [comment]
Ah, it seems like I've made a small mistake in the library. It should be fixed soon. Thanks for the issue report!

**Comment by Sajidur78** [comment]
The issue should be fixed on 3165326615fce9c81c29309dfe22d8d9928de072. I will update the nuget package if the issue is resolved on your end.

**Comment by alexamiryan** [comment]
Thank you very much, I will report back on Monday.

**Comment by alexamiryan** [comment]
It works! You can update nuget package. Thanks a lot!
