### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by subu1979** [Sajidur78/CredNet#10]
Hi,

Cloned & Re-builed the code in VS-2017.

On a virtual box (Windows 10), i have installed the Credential Provider using Install.reg. When i restart / Sign-out  the System,  could not see the NEW Credential Provider.

**Comment by Sajidur78** [comment]
Hi, make sure the credential provider assembly is registered to COM otherwise it won't show up. The assembly can be registered using `regasm` or with an [installer project](https://github.com/Sajidur78/CredNet/tree/master/Samples/CredNet.Sample.Setup).

**Comment by subu1979** [comment]
Thanks.
