### ISSUE TITLE
Network Ethernet Disabled Dont Logon Domain Active Logon Password Problem and dont error message or logon

### ISSUE THREAD

**Issue by dogansoft** [Sajidur78/CredNet#5]
Dear Friends;

İ tested windows default provider network Ethernet Disabled Active Domain User write password logon.

but CredNet provider Dont Logon

Please Help me

thanks
best regards

**Comment by Sajidur78** [comment]
From my testing I wasn't able to replicate issue. There could be a problem with your code and not the library.

**Comment by dogansoft** [comment]
> Testlerimden sorunu tekrarlayamadım. Kitaplıkla değil, kodunuzla ilgili bir sorun olabilir.

im sorry. ı'm bad english language. I Say you step by step

1) Your Computer Ethernet Disable
2) Please test now your computer Windows Logon Screen,  Your Provider use logon Active Directory
I tested but dont login(Show Username or password Error Message). I tested windows original provider No Problem

i hope understand me

thanks
best regards
