### ISSUE TITLE
Please Help Me

### ISSUE THREAD

**Issue by dogansoft** [Sajidur78/CredNet#6]
Dear Developer;

please help me. How to add Provider Filter. Please send me example or say me

thanks
best regards

**Comment by Sajidur78** [comment]
Hi, currently provider filters are not supported by the library. However, it should be implemented by tomorrow or the day after.

**Comment by Sajidur78** [comment]
Filter classes has been added in ff04516ad34a3983b2c0a8c8d55da748b91c1ffe. Here is an example implementation.
```cs
using System;
using CredNet;
using CredNet.Interop;
using System.Runtime.InteropServices;

[ComVisible(true)]
[ClassInterface(ClassInterfaceType.None)]
[ProgId("CredNet.Sample")]
[Guid("0522331e-f32d-4e5b-8c76-8267f0d5b50e")]
public class CredentialProviderFilterSample : CredentialProviderFilterBase
{
    public override bool IsProviderAllowed(UsageScenario scenario, CredUI.Flags uiFlags, ref Guid clsIdProvider)
    {
        // Allow all providers for this sample
        return true;
    }

    public override ManagedCredentialSerialization UpdateRemoteCredential(ManagedCredentialSerialization inputSerialization)
    {
        // Unimplemented for this sample
        throw new NotImplementedException();
    }
}
```


Similar to providers, filters also have to be added to the registry. Filters go in the following registry key.
```HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\Credential Provider Filters```
