### ISSUE TITLE
how to auto unlock the windows screen when using LockWorkStation api?

### ISSUE THREAD

**Issue by xeon-ye** [Sajidur78/CredNet#9]
I use NamedPipe to pass the username,password to the credential, and call Provider.RaiseCredentialsChanged() but nothing happened,how to auto unlock the windows screen after using LockWorkStation api?

**Comment by Sajidur78** [comment]
Hi, before calling RaiseCredentialsChanged make sure you're setting Provider.DefaultCredential and setting AutoLogon to true.

**Comment by xeon-ye** [comment]
got it! thank you very much!
